version: "3"
services:
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    environment:
      MB_DB_TYPE: "${MB_DB_TYPE}"
      MB_DB_DBNAME: "${MB_DB_DBNAME}"
      MB_DB_PORT: "${MB_DB_PORT}"
      MB_DB_USER: "${MB_DB_USER}"
      MB_DB_PASS: "${MB_DB_PASS}"
      MB_DB_HOST: "${MB_DB_HOST}"
    restart: always
    ports:
      - ${MB_PORT}:8080
