# change .env files before running!

services:
  jupyter:
    image: ${JUPYTER_IMAGE}
    container_name: jupyter
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    volumes:
      - /data/jupyter:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}

# mkdir -p /data/jupyter; chown -R 1000:100 /data/jupyter
# docker run -it -p 8888:8888 -v /data/jupyter:/home/jovyan/work -e JUPYTER_TOKEN=pigsty -name jupyter jupyter/minimal-notebook