# check .env files before running
version: "3"
services:
  bytebase:
    container_name: bytebase
    image: bytebase/bytebase:latest
    restart: unless-stopped
    ports:
      - "${BB_PORT}:${BB_PORT}"
    command: |
      --external-url ${BB_DOMAIN} --port ${BB_PORT} --pg=${BB_PGURL}