version: "3"
services:
  pg_exporter:
    container_name: pg_exporter
    image: vonng/pg_exporter
    restart: always
    environment:
      PG_EXPORTER_URL: ${PG_EXPORTER_URL}
      PG_EXPORTER_CONFIG: ${PG_EXPORTER_CONFIG}
      PG_EXPORTER_LABEL: ${PG_EXPORTER_LABEL}
      PG_EXPORTER_TAG: ${PG_EXPORTER_TAG}
      PG_EXPORTER_DISABLE_CACHE: ${PG_EXPORTER_DISABLE_CACHE}
      PG_EXPORTER_DISABLE_DEFAULT_METRICS: ${PG_EXPORTER_DISABLE_DEFAULT_METRICS}
      PG_EXPORTER_AUTO_DISCOVERY: ${PG_EXPORTER_AUTO_DISCOVERY}
      PG_EXPORTER_EXCLUDE_DATABASE: ${PG_EXPORTER_EXCLUDE_DATABASE}
      PG_EXPORTER_INCLUDE_DATABASE: ${PG_EXPORTER_INCLUDE_DATABASE}
      PG_EXPORTER_NAMESPACE: ${PG_EXPORTER_NAMESPACE}
      PG_EXPORTER_FAIL_FAST: ${PG_EXPORTER_FAIL_FAST}
      PG_EXPORTER_CONNECT_TIMEOUT: ${PG_EXPORTER_CONNECT_TIMEOUT}
      PG_EXPORTER_LISTEN_ADDRESS: ${PG_EXPORTER_LISTEN_ADDRESS}
      PG_EXPORTER_TELEMETRY_PATH: ${PG_EXPORTER_TELEMETRY_PATH}

      #PG_EXPORTER_URL: 'postgres://dbuser_monitor:DBUser.Monitor@10.10.10.10:5432/postgres?sslmode=disable'
      #PG_EXPORTER_CONFIG: '/etc/pg_exporter.yml'
      #PG_EXPORTER_LABEL: ""
      #PG_EXPORTER_TAG: ""
      #PG_EXPORTER_DISABLE_CACHE: 'false'
      #PG_EXPORTER_DISABLE_DEFAULT_METRICS: 'false'
      #PG_EXPORTER_AUTO_DISCOVERY: 'true'
      #PG_EXPORTER_EXCLUDE_DATABASE: "template0,template1,postgres"
      #PG_EXPORTER_INCLUDE_DATABASE: ""
      #PG_EXPORTER_NAMESPACE: "pg"
      #PG_EXPORTER_FAIL_FAST: 'false'
      #PG_EXPORTER_CONNECT_TIMEOUT: '100'
      #PG_EXPORTER_LISTEN_ADDRESS: ":9630"
      #PG_EXPORTER_TELEMETRY_PATH: "/metrics"
    ports:
      - "${PG_EXPORTER_PORT}:9630"
