---
galaxy_info:
  role_name: pgsql
  description: init postgres on pigsty node
  min_ansible_version: "2.9"
  author: 'Ruohang Feng'
  license: GPLv3
  platforms:
    - name: EL
      versions: [ 7, 8 , 9 ]
    - name: Ubuntu
      versions: [ 22.04, 20.04 ]
    - name: Debian
      versions: [ 12, 11 ]
  galaxy_tags:
    - pigsty
    - pgsql
    - postgres
    - patroni
    - pgbouncer
    - pgbackrest
...