---
#--------------------------------------------------------------#
# Gather PG Node Spec                                  [pg_spec]
#--------------------------------------------------------------#
- name: get postgres node facts
  tags: [ pg_conf, pg_spec ]
  block:

    # cpu core number | page count | page size | avail 1k-block count for pg_fs_main
    # it may raise error due to pg_fs_main not exists, which really should raise an error!
    - name: get node basic facts
      shell: echo "$(grep -c '^processor' /proc/cpuinfo) $(getconf _PHYS_PAGES) $(getconf PAGE_SIZE) $(df {{ pg_fs_main }} --o=size | tail -1)"
      register: pg_node_fact
      args: { executable: /bin/bash }

    # USE node_id ROLE TO GATHER NODE SPEC
    # if pg_fs_main size is missing, use 40GB as estimation
    - name: calculate node parameters
      connection: local
      set_fact:
        #node_cpu: "{% set fact_list = pg_node_fact.stdout.split() %}{{ fact_list[0]|int }}"
        #node_mem_bytes: "{% set fact_list = pg_node_fact.stdout.split() %}{{ (fact_list[1]|int * fact_list[2]|int)|int }}"
        #node_mem_mb: "{% set fact_list = pg_node_fact.stdout.split() %}{{ ((fact_list[1]|int * fact_list[2]|int)|int / 1048576)|round(0, 'ceil')|int }}"
        #node_mem_gb: "{% set fact_list = pg_node_fact.stdout.split() %}{{ [ ((fact_list[1]|int * fact_list[2]|int)|int / 1073741824)|round(0, 'ceil')|int , 1 ] | max }}"
        node_fs_bytes: "{% set fact_list = pg_node_fact.stdout.split() %}{% if fact_list|length >= 4%}{{ fact_list[3]|int * 1024 }}{% else %}42949672960{% endif %}"

    # print cpu, mem, disk info
    - name: print postgres node spec
      connection: local
      debug:
        msg: "Node={{ node_cpu }}c{{ node_mem_gb }}g {{ node_tune }}, Memory={{ (node_mem_mb|int / 400 | round(0, 'ceil'))|int * 100 }}MB of {{ node_mem_mb }}MB , Disk={{ [ (node_fs_bytes|int / 1073741824)|round(0, 'ceil')|int , 1 ] | max }}GB {{ pg_storage_type|default('SSD') }} @ {{ pg_fs_main }}, PG Conf={{ pg_conf }}"


#--------------------------------------------------------------#
# Config Patroni                                       [pg_conf]
#--------------------------------------------------------------#
- name: render patroni config
  tags: pg_conf
  block:

    - name: render patroni default config
      template:
        src: "{{ item }}"
        dest: "/pg/conf/{{ item }}"
        owner: "{{ pg_dbsu }}"
        group: postgres
        mode: 0755
      with_items: [ oltp.yml ,olap.yml ,crit.yml ,tiny.yml ]

    - name: render patroni customize config
      when: pg_conf not in [ 'oltp.yml' , 'olap.yml' , 'crit.yml', 'tiny.yml' ]
      template:
        src: "{{ pg_conf }}"
        dest: "/pg/conf/{{ pg_conf }}"
        owner: "{{ pg_dbsu }}"
        group: postgres
        mode: 0755

    # /etc/patroni/patroni.yml -> /pg/bin/patroni.yml -> /pg/conf/{{ pg_instance }}.yml
    - name: use patroni config
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ pg_dbsu }}"
        group: postgres
        state: link
      with_items:
        - { src: "/pg/conf/{{ pg_conf }}"         , dest: "/pg/conf/{{ pg_instance }}.yml" }
        - { src: "/pg/conf/{{ pg_instance }}.yml" , dest: "/pg/bin/patroni.yml" }
        - { src: "/pg/bin/patroni.yml"            , dest: "/etc/patroni/patroni.yml" }

#--------------------------------------------------------------#
# Systemd Service                                   [pg_systemd]
#--------------------------------------------------------------#
- name: create patroni systemd service
  tags: pg_systemd
  template:
    src: "{{ item }}.service.j2"
    dest: "{{ systemd_dir }}/{{ item }}.service"
  with_items: [ patroni, postgres ]
  vars: { systemd_dir: "{% if os_package is defined and os_package == 'deb' %}/lib/systemd/system/{% else %}/usr/lib/systemd/system{% endif %}" }



#--------------------------------------------------------------#
# Config PgBackrest Bootstrap repo           [pgbackrest_config]
#--------------------------------------------------------------#
# this config is render for bootstrap / replica creation only
- name: config pgbackrest
  tags: pg_backup_conf
  when: pgbackrest_enabled|bool
  block:

    - name: remove unused pgbackrest.conf file
      file: path=/etc/pgbackrest.conf state=absent

    - name: render pgbackrest config
      template: src=pgbackrest.conf.j2 dest=/etc/pgbackrest/pgbackrest.conf owner=postgres group=postgres mode=0600


...