---
#--------------------------------------------------------------#
# Generate Business Database Config               [pg_db_config]
#--------------------------------------------------------------#
- name: generate postgres business database config
  tags: [ pg_db , pg_db_config ]
  when: pg_role == 'primary'
  block:

    - name: render sql for database {{ database.name }}
      tags: pg_db_config
      template: src="pg-db.sql" dest=/pg/tmp/pg-db-{{ database.name }}.sql owner={{ pg_dbsu|default('postgres') }} group=postgres mode=0755

    - name: copy baseline for database {{ database.name }}
      tags: pg_db_config
      when: database.baseline is defined
      copy: src="{{ database.baseline }}" dest=/pg/tmp/pg-db-{{ database.name }}-baseline.sql owner={{ pg_dbsu|default('postgres') }} group=postgres mode=0755


#--------------------------------------------------------------#
# Create Business Database                        [pg_db_create]
#--------------------------------------------------------------#
- name: create postgres business database
  tags: [ pg_db, pg_db_create ]
  when: pg_role == 'primary'
  block:
    # create database with shell command, check database exists as success
    - name: create database {{ database.name }}
      tags: pg_db_create
      ignore_errors: true
      become_user: "{{ pg_dbsu|default('postgres') }}"
      shell: |
        createdb -w -h {{ pg_localhost|default('/var/run/postgresql') }} -p {{ pg_port|default(5432) }} {% if 'owner' in  database and database.owner != '' %}-O "{{ database.owner }}" {% endif %}
        {% if 'template'   in  database and database.template != ''   %}-T '{{ database.template   }}' {% endif %}
        {% if 'encoding'   in  database and database.encoding != ''   %}-E '{{ database.encoding   }}' {% endif %}
        {% if 'locale'     in  database and database.locale != ''     %}-l '{{ database.locale     }}' {% endif %}
        {% if 'tablespace' in  database and database.tablespace != '' %}-D '{{ database.tablespace }}' {% endif %}
        '{{ database.name }}' || true
        db_exists=$(psql -h {{ pg_localhost|default('/var/run/postgresql') }} -p {{ pg_port|default(5432) }} -AXtwq postgres -c "SELECT true WHERE EXISTS(SELECT * FROM pg_database WHERE datname = '{{ database.name }}' LIMIT 1);")
        [[ -z "${db_exists}" ]] && exit 1 || exit 0
      args: { executable: /bin/bash }

    - name: provision database {{ database.name }}
      tags: pg_db_create
      ignore_errors: true
      become_user: "{{ pg_dbsu|default('postgres') }}"
      command: psql {{ database.name }} -h {{ pg_localhost|default('/var/run/postgresql') }} -p {{ pg_port|default(5432) }} -AXtwqf /pg/tmp/pg-db-{{ database.name }}.sql

    - name: load database {{ database.name }} baseline
      tags: pg_db_create
      ignore_errors: true
      become_user: "{{ pg_dbsu|default('postgres') }}"
      command: psql {{ database.name }} -h {{ pg_localhost|default('/var/run/postgresql') }} -p {{ pg_port|default(5432) }} -AXtwqf /pg/tmp/pg-db-{{ database.name }}-baseline.sql
      when: database.baseline is defined

...