---
#--------------------------------------------------------------#
# Firewall & SELinux                             [node_firewall]
#--------------------------------------------------------------#
# This behaviour may be changed in the future
# It's acceptable to use this in isolated network environment
- name: disable node firewall
  tags: node_firewall
  ignore_errors: true
  block:

    # - disable firewalld / ufw - #
    - name: disable node firewalld
      when: node_disable_firewall|bool and (os_package == 'rpm' or os_vendor == 'ubuntu')
      systemd: name={{ firewall_service_name }} state=stopped enabled=no
      vars: { firewall_service_name: "{% if os_package is defined and os_package == 'deb' %}ufw{% else %}firewalld{% endif %}" }

    # - disable selinux on el - #
    - name: disable node selinux
      when: node_disable_selinux|bool and os_package == 'rpm'
      shell: |
        setenforce 0;
        sed -ie "s/^SELINUX=.*/SELINUX=disabled/g" /etc/selinux/config;
        rm -rf /etc/selinux/confige; /bin/true
      args: { executable: /bin/bash }
...